import enum


class RegistryErrorCodes(enum.Enum):
    """
    Error codes that can be returned from the registry.
    Corresponding catalog in the registry: dev/jcri/mdde/registry/exceptions/EErrorCode.java
    """
    RUNTIME_ERROR = 0x00
    UNSPECIFIED_ERROR = 0x0270F

    DUPLICATE_ENTITY = 0x0834
    UNKNOWN_ENTITY_ID = 0x0835

    UNKNOWN_COMMAND = 0x0899
    MISSING_COMMAND_ARGUMENT = 0x089A

    READ_OPERATION_ERROR = 0x08FC
    WRITE_OPERATION_ERROR = 0x08FD

    RESPONSE_SERIALIZATION_ERROR = 0x092E

    REGISTRY_MODE_ALREADY_SET = 0x09C4
    INCORRECT_REGISTRY_MODE_FOR_OPERATION = 0x09C5

    DUPLICATE_FRAGMENT_REPLICATION = 0x0A29
    LOCAL_FRAGMENT_REPLICATION = 0x0A2A
    NON_COLOCATED_FRAGMENT_FORMATION = 0x0A2B
    UNIQUE_FRAGMENT_REMOVAL = 0x0A2C
    SEED_NON_EMPTY_REGISTRY = 0x0A2D

    DATA_KEY_NOT_FOUND = 0x0C1C

    CTRL_ILLEGAL_COMMAND_ARGUMENT = 0x01004
    CTRL_MALFORMED_COMMAND_STATEMENT = 0x01005
