from typing import NamedTuple, Union

from mdde.registry.workload import EYCSBWorkloadRequestDistribution


class YCSBWorkloadInfo(NamedTuple):
    """Basic relevant information about a YCSB workload."""

    tag: Union[None, str]
    """Tag used to invoke the workload via the registry control API, none for a custom workload"""
    request_distribution: EYCSBWorkloadRequestDistribution
    """Request distribution"""
    read_all_fields: bool = True
    record_count: int = 0
    """Number of the data records generated by the workload"""
    operation_count: int = 0
    """Total number of operations"""

# At the moment MDDE does not support insert, update or delete operations in the workloads, assumed read operations
# proportion is 1.0
